language: objective-c
osx_image: xcode7.3
xcode_project: NEKit.xcodeproj
xcode_scheme:
  # - NEKit-iOS
  - NEKit-OSX
cache:
  directories:
    - Carthage

install:
  - carthage bootstrap --no-use-binaries --platform mac,ios
